# Generated by Django 4.2.29 on 2026-03-31 01:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investments', '0002_investmentplan_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoTicker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(help_text='Trading symbol, e.g. BTC, ETH', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Display name, e.g. Bitcoin, Ethereum', max_length=100)),
                ('coingecko_id', models.CharField(help_text='CoinGecko coin ID (e.g. bitcoin, ethereum)', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Crypto Ticker',
                'verbose_name_plural': 'Crypto Tickers',
                'ordering': ['display_order', 'symbol'],
            },
        ),
        migrations.AddField(
            model_name='agentapplication',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='walletaddress',
            name='network',
            field=models.CharField(blank=True, help_text='e.g., ERC-20, TRC-20, BEP-20', max_length=50),
        ),
        migrations.AddField(
            model_name='walletaddress',
            name='qr_code_image',
            field=models.ImageField(blank=True, null=True, upload_to='wallets/qr/'),
        ),
        migrations.AlterField(
            model_name='walletaddress',
            name='crypto_type',
            field=models.CharField(choices=[('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('USDT', 'Tether (USDT)'), ('USDC', 'USD Coin'), ('LTC', 'Litecoin'), ('BNB', 'Binance Coin'), ('BANK', 'Bank Transfer')], max_length=10, unique=True),
        ),
    ]
