# Generated by Django 4.2.29 on 2026-03-27 23:38

import accounts.site_settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_update_min_deposit_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='enable_live_chat',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='smartsupp_api_key',
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='company_address',
            field=models.TextField(default='London, United Kingdom'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='company_email',
            field=models.EmailField(default='admin@elitewealthcapita.uk', max_length=254),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='company_phone',
            field=models.CharField(default='+44 20 7946 0958', max_length=20),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='copyright_text',
            field=models.CharField(default=accounts.site_settings._default_copyright_text, max_length=200),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['user', 'created_at'], name='accounts_ac_user_id_df2351_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['action'], name='accounts_ac_action_fde492_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['created_at'], name='accounts_ac_created_936747_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['email'], name='accounts_cu_email_5ce40b_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['kyc_status'], name='accounts_cu_kyc_sta_9cf458_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['date_joined'], name='accounts_cu_date_jo_fcefff_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['referral_code'], name='accounts_cu_referra_4d2021_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['referrer', 'status'], name='accounts_re_referre_92276f_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['status'], name='accounts_re_status_e6cd4e_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['created_at'], name='accounts_re_created_f889b0_idx'),
        ),
    ]
